matrix-transposer.py

Adds code to transpose a matrix

Transpose Matrix Feature

---

matrix-transposer-list-comp.py

Adds program to transpose a matrix using list comprehension

Matrix transpose using list comprehension

---

vowel-occurence-counter.py

Adds code to count the occurrence of each vowel in a sentence

Feat: code to count the occurrence of each vowel

---

add-vowel-occurence-counter-list-comp.py

adds code to count the number of times each unique vowel occurs using list comprehension

Feat: vowel occurence counter using list comprehension

---

card-deck-shuffler.py

Add code to shuffle a deck of card

Card deck shuffler Implementation

---

leap-year-checker.py

This PR contains code that checks for a leap year

Add leap year checker

---

armstrong-between-interval-finder.py

This PR contains code to check armstrong numbers in a certain interval

Add armstrong between interval finder

---

alphabetical-word-sorter.py

This PR contains program to sort alphabetically the words form a string provided by the user

feat: sort alphabetically the words form a string

---

set-operations-showcase
set-operations-showcase.py

Add code to show examples of python set operations

Add set operations showcase

---

img-resolution-finder.py

This PR adds code to Find the Size (Resolution) of an Image

Add img resolution finder

---

mail-merger.py

This PR adds a program to merge mail

Mail merger feature

---

file-hash-computer.py

This PR adds code to find the SHA-1 message digest of a file

Add file hash computer

---

file-lines-counter.py

This PR adds multiple ways to count the number of lines in a file

Add file lines counter

---

anagram-checker.py

This PR adds a program to check if two strings are anagrams

Add anagram checker

---

string-permutations-computer.py

This PR adds a Program to Compute all the Permutation of the String

Program to Compute all the Permutation of the String

---

compound-interest-calculator.py

This PR adds code to find compound interest with parameters inputed by the user

Add compound interest calculator

---

num-divisible-by-digits-checker.py

This PR adds a program to check the number is divisible by all digits are not.

Add num divisible by digits checker

---

num-in-a-base-consecutive-zeros-checker.py

This PR adds code to check whether a number has consecutive 0’s in the given base or not

Add num in a base consecutive zeros checker

---

num-binary-palindrome-checker.py

This PR adds a program to check if binary representation of a number is palindrome or not

Add num binary palindrome checker

---

num-unique-prime-factors-product-calculator.py

This PR adds code to find product of unique prime factors of a number

Add num unique prime factors product calculator

---

min-sum-of-a-num-factors-calculator.py

This PR adds a Program to Find minimum sum of factors of number

Add  min sum of a num factors calculator

---

num-largest-prime-factor-finder.py

This PR adds a program to find the largest prime factor of a number

num largest prime factor finder

---

efficient-num-prime-factors-printer.py

This PR adds a program to Efficiently print all prime factors of a given number

prime factors printer

---

position-of-a-num-nth-multiple-in-fibonacci-series-finder.py

This PR adds a code to implement a program for nth multiple of a number in Fibonacci Series

feat: implement the logic for this feature branch

---

every-day-of-the-year-occurrence-counter.py

This PR adds a program to Find number of times every day occurs in a Year

Feature : every day of the year occurrence counter

---

lap-timer.py

This PR adds a code that implements a lap timer logic in the CLI

feat: lap timer implementation

---

gcd-calculator.py

This PR adds code to implement the logic to find GCD of two numbers

feat: implement the logic to find GCD of two numbers

---

sundays-in-a-year-printer.py

This PR adds code to add code to print all Sundays in a year

feat: add code to print all sundays in a year

---

three-column-calendar-printer.py

This PR adds code to print calendar in which all months of the year are arranged in 3 columns

feat: add code to print 3 column calendar for a year

---

every-n-days-printer.py

This PR prints a specified count of every next n dates from an initial date

feat: every n days printer starting from a date

---

last-weekday-date-printer.py

This PR adds code to print the date of the last weekday( e.g. last Tuesday, last Saturday )

feat: add code to print the date of last weekday

---

age-calculator.py

This PR adds code to calculate a persons age provided the date of birth

feat: add code to calculate age from dob

---

position-of-uppercase-vowels-in-even-indices-finder.py

This PR adds code to find the position of uppercase vowels in even indices of a string

feat: code to find position of uppercase vowels in even indices

---

triangle-length-of-sides-to-coordinates-converter.py

This PR adds a code to get the coordinates of a triangle from all lengths of its sides starting from (0,0)

feat: code to get triangle coordinates from the length of its sides

---

sum-of-first-n-nums-with-more-than-2-digits.py

This PR adds code to find the sum of the numbers among the first k with more than 2 digits

feat: calculate sum of first n nums with more than 2 digits

---

snippets/check-list-length-and-count-of-nth-element.py

This PR adds code to check the length of a list and the count of the list nth element

feat: code to check list length and count of nth element

---

convert-two-date-diff-in-days-hours-minutes-seconds.py

This PR adds code to convert the difference between two dates into days hours minutes seconds

feat: code to convert two date diff into days hours minutes seconds

---

add-years-to-date.py

This PR contains code to add year(s) to a given date and display the new date

feat: add code to add years to a date

---

index-of-largest-prime-in-list-and-the-sum-of-its-digits.py

Find the index of the largest prime in the list and the sum of its digits

feat: code to find index of largest prime in the list and the sum of its digits

---

snippets/find-nums-greater-than-n-and-have-odd-first-and-last-digits

This PR adds code to Find the numbers that are greater than n and have odd first and last digits

feat: code to find nums greater than n and have odd first and last digits

---

compute-string-separated-by-space-from-given-char-counts.py

This PR adds a code snippet to compute string separated by space from given char counts

feat: code to compute string separated by space from given char counts

---

product-of-the-odd-digits-of-a-num.py

This PR adds code calculate the product of the odd digits of a number

feat: code to calculate product of the odd digits of a number

---

snippets/check-if-sum-of-triples-is-zero.py

This PR checks for multiple inner lists in a list, if the sum of triple numbers in the inner list is zero

feat: check if sum of triple numbers is zero

---

snippets/check-if-sum-of-first-n-integers-is-n.py

This PR contains code that checks if sum of first n integers in a list is n

feat: check if sum of first n integers is n

---

snippets/check-if-sum-of-first-n-integers-is-n.py

This PR lets the user provide the required parameters

refactor: let the user provide the required parameters

---

snippets/check-if-sum-of-first-n-integers-is-n.py

This PR updates output error message and cleans up the code comment

refactor: update error message and cleanup comment

---

third-tuesday-of-a-month-checker.py

This PR removes unnecessary code comment and formats the code properly

refactor: remove unneeded comment and format code properly

---

product-of-the-odd-digits-of-a-num.py

This PR cleans up the code and gets the input from the user in lieu of a constant

Cleanup - product of the odd digits of a num

---

snippets/find-nums-greater-than-n-and-have-odd-first-and-last-digits.py

This PR lets users provide the programs required parameters

refactor: let user provide the required parameters

---

js/js/find-most-consecutive-repeating-prefix.js

This PR adds a js code to find most consecutive repeating prefix in a string list

feat: code to find most consecutive repeating prefix in a string list

---

py/utils/input_utils.py

add utility file that contains  to get number list from user

feat: add util to get number list from user

---

codes/py/snippets/find-nums-greater-than-n-and-have-odd-first-and-last-digits.py

This PR uses `inpututils.get_number_list_interactively` to get the lists of number from the user

refactor: use inpututil to get number lists from user

---

codes/py/snippets/check-if-sum-of-first-n-integers-is-n.py

This PR uses the input utils library to get the list of numbers from the user.

refactor: use input utils library

---

codes/py/snippets/check-if-sum-of-first-n-integers-is-n.py

refactor: cleanup the code

---

codes/py/utils/input_utils.py

This PR fixes a bug in input utils in which it does not allow negative numbers in the input list

fix: make input utils accept negative numbers

---

codes/py/snippets/check-list-length-and-count-of-nth-element.py
codes/py/utils/number_utils.py

This PR uses user input for various vars and creates a class containing various number utils

Refactor : use user input for vars and create number utils class

---

codes/py/snippets/change-the-position-of-every-nth-value-with-the-next.py

This PR gets the list of numbers needed by `codes/py/snippets/change-the-position-of-every-nth-value-with-the-next.py` from the user instead of being hardcoded.

refactor: get list of numbers from the user

---

codes/py/index-of-largest-prime-in-list-and-the-sum-of-its-digits.py

This PR removes boilerplate to get list of numbers from the user and replaces it with `input_utils` library

refactor: use input_utils lib

---

codes/py/triangle-length-of-sides-to-coordinates-converter.py
codes/py/utils/input_utils.py

This PR:
1) replaces hardcoded array with user input.
2) extends input_utils by parameterizing presentation messages

Refactor: replace hardcoded array with user input

---

codes/py/indices-of-two-nums-that-sum-to-zero-finder.py

This PR gets the list of numbers from the user through input_utils

refactor: get number list from the user
